### PR TITLE
[NOT READY] Update visual images with harfbuzz 1.0.5

### PR DESCRIPTION
**Pull request by springmeyer**
When we decide to upgrade harfbuzz to 1.x in [bootstrap.sh](https://github.com/mapnik/mapnik/blob/a73e8537d81f4551b87abb223f04ff56de9b1570/bootstrap.sh#L58) then we'll need to merge this to keep visual tests passing.

This is because somewhere between harfbuzz 0.9.x and 1.x subtle differences appear in font positioning.

/cc @artemp @talaj @flippmoke @BergWerkGIS

### CODE REVIEW

**Comment by springmeyer** [comment]
@behdad - no action needed here on your part. But cc'ing you just in case you are interested these differences. To recap: the Mapnik visual test suite captures pixel differences. One goal of this is so that we can understand when dependencies of Mapnik might change the look of rendered maps. I've never seen changes before due to harfbuzz - this is the first time an upgrade has triggered visual differences. They mostly look minor and okay, but I'll be investigating more when I have time.

**Comment by artemp** [comment]
@springmeyer - I've been using harfbuzz-1.0.4 for a while and I didn't see any visual test related issues - is this for 1.0.5 only ? 
`<rant> visual tests are so fragile</rant>`

**Comment by springmeyer** [comment]
> @springmeyer - I've been using harfbuzz-1.0.4 for a while and I didn't see any visual test related issues - is this for 1.0.5 only ? 

Oh, interesting! I only tested with `v1.0.5` so perhaps it is some change in harfbuzz within the 1.x series and not between that and v0.9.x. I'll take a closer look.

> <rant> visual tests are so fragile</rant>

By design! Just to be clear: I like the fact that I noticed this and that I had to create this ticket to prepare for migrating the tests to a new harfbuzz version. If you don't like the design then revisit  https://github.com/mapnik/mapnik/issues/3049#issuecomment-135879504 and let's discuss there.

**Comment by springmeyer** [comment]
>  I've been using harfbuzz-1.0.4 for a while and I didn't see any visual test related issues - is this for 1.0.5 only ?

Confirmed: the change impacting visual results happened between harfbuzz v1.0.4 and v1.0.5.

I suspected https://github.com/behdad/harfbuzz/commit/88da7bba9fa4665b33f5bfcd45add7443097eaf3 after looking through [recent commits](https://github.com/behdad/harfbuzz/commits/master), but that does not appear to be the change. Something else...

**Comment by springmeyer** [comment]
Narrowed down to https://github.com/behdad/harfbuzz/commit/2a9627c5641cd000e2adff0e42a0dc687b53ec70.

This patch fixes all visual tests:

``` diff
diff --git a/include/mapnik/text/harfbuzz_shaper.hpp b/include/mapnik/text/harfbuzz_shaper.hpp
index ac436a1..f1f6dbf 100644
--- a/include/mapnik/text/harfbuzz_shaper.hpp
+++ b/include/mapnik/text/harfbuzz_shaper.hpp
@@ -101,6 +101,7 @@ static void shape_text(text_line & line,
             hb_buffer_set_direction(buffer.get(), (text_item.dir == UBIDI_RTL)?HB_DIRECTION_RTL:HB_DIRECTION_LTR);
             hb_buffer_set_script(buffer.get(), _icu_script_to_script(text_item.script));
             hb_font_t *font(hb_ft_font_create(face->get_face(), nullptr));
+            hb_ft_font_set_load_flags(font,FT_LOAD_DEFAULT | FT_LOAD_NO_HINTING);
             hb_shape(font, buffer.get(), ff_settings.get_features(), ff_count);
             hb_font_destroy(font);

```

**Comment by springmeyer** [comment]
solved via mapnik core change. closing.

**Comment by behdad** [comment]
Yes, sorry about that.  I was undecided whether to make this change of behavior or not.  Still not sure how many peoples' code it's breaking.  Humm..  The OCD side of me wanted to keep FT_LOAD_DEFAULT as default...

**Comment by behdad** [comment]
WDYT, should I change it back?

**Comment by behdad** [comment]
I'm reverting the behavior change in HB.  See: https://github.com/behdad/harfbuzz/issues/143

**Comment by springmeyer** [comment]
@behdad - hi, just seeing your comments now - Thank you for letting me know about the revert. I've adapted upstream to use the new API in https://github.com/mapnik/mapnik/commit/5da6563db48310fc63e483dfa6012bdd964013db, which is great. But yes, I agree with the revert still as those defaults seem sensible.

**Pull request closed without merging**
